<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title></title>
  <style type="text/css">code{white-space: pre;}</style>
  <style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
  </style>
  <link rel="stylesheet" href="/style.css" type="text/css" />
</head>
<body>
<div id="TOC">
<ul>
<li><a href="#exception-and-control-flow">Exception and Control Flow</a><ul>
<li><a href="#example-control_flow_demo.py">Example :control_flow_demo.py</a></li>
<li><a href="#handling-exceptions">Handling Exceptions</a><ul>
<li><a href="#example-handle_exception_demo.py">Example handle_exception_demo.py</a></li>
<li><a href="#type_error.py">type_error.py</a></li>
<li><a href="#except_tuple.py">except_tuple.py</a></li>
</ul></li>
<li><a href="#exceptions-for-programmer-errors">Exceptions for programmer errors</a></li>
<li><a href="#handle-empty-except-block">Handle empty except block</a></li>
<li><a href="#exception-object-exception_object.py">Exception object (exception_object.py)</a></li>
<li><a href="#re-raising-exceptions-raise_demo.py">Re-Raising Exceptions (raise_demo.py)</a></li>
<li><a href="#returning-exception-objects">Returning exception objects</a><ul>
<li><a href="#raise_demo_1.py">raise_demo_1.py</a></li>
<li><a href="#raise_demo_2.py">raise_demo_2.py</a></li>
</ul></li>
<li><a href="#finally-block">Finally block</a></li>
<li><a href="#summary">Summary</a></li>
<li><a href="#exisiting-exceptions">Exisiting Exceptions</a><ul>
<li><a href="#index"><a href="index.html">index</a></a></li>
</ul></li>
</ul></li>
</ul>
</div>
<h1 id="exception-and-control-flow">Exception and Control Flow</h1>
<p>Example that effects the control flow</p>
<h2 id="example-control_flow_demo.py">Example :control_flow_demo.py</h2>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    x <span class="op">=</span> <span class="bu">int</span>(s)
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;10&quot;</span>))
    <span class="co"># This will cause exception</span>
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;Hello world&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Convert</span> String to int 10
<span class="ex">Traceback</span> (most recent call last)<span class="bu">:</span>
    <span class="ex">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;Hello world&quot;</span>))
      <span class="ex">x</span> = int(s)
<span class="ex">ValueError</span>: invalid literal for int() <span class="ex">with</span> base 10: <span class="st">&#39;Hello world&#39;</span></code></pre></div>
<ul>
<li><strong>ValueError</strong> is exception object</li>
<li><strong>invalid literal for int()</strong> payload of the exception object</li>
</ul>
<h2 id="handling-exceptions">Handling Exceptions</h2>
<p>Both the try and except keywords introduce new blocks.</p>
<ul>
<li>The <strong>try</strong> block contains code that could raise an exception</li>
<li><strong>except</strong> block contains the code which performs error handling in the event that an exception is raised<br />
<strong>Note:</strong> The statements in the try block after the point at which the exception was raised was not executed</li>
</ul>
<h3 id="example-handle_exception_demo.py">Example handle_exception_demo.py</h3>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">try</span>:
         x <span class="op">=</span> <span class="bu">int</span>(s)
         <span class="bu">print</span>(<span class="st">&quot;Conversion is successful!&quot;</span>)
    <span class="cf">except</span> <span class="pp">ValueError</span>:
        x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
        <span class="bu">print</span>(<span class="st">&quot;Conversion is failed!&quot;</span>)
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;10&quot;</span>))
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;Hello world&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Conversion</span> is successful!
<span class="ex">Convert</span> String to int 10
<span class="ex">Conversion</span> is failed!
<span class="ex">Convert</span> String to int -1</code></pre></div>
<h3 id="type_error.py">type_error.py</h3>
<p>Handle the wrong types that was passed. User is passing list of integers instead of int</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">try</span>:
         x <span class="op">=</span> <span class="bu">int</span>(s)
         <span class="bu">print</span>(<span class="st">&quot;Conversion is successful!&quot;</span>)
    <span class="cf">except</span> <span class="pp">ValueError</span>:
        x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
        <span class="bu">print</span>(<span class="st">&quot;Conversion is failed!&quot;</span>)
    <span class="cf">except</span> <span class="pp">TypeError</span>:
        x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
        <span class="bu">print</span>(<span class="st">&quot;Conversion failed. Wrong Type!&quot;</span>)
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;10&quot;</span>))
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Conversion</span> is successful!
<span class="ex">Convert</span> String to int 10
<span class="ex">Conversion</span> failed. Wrong Type!
<span class="ex">Convert</span> String to int -1</code></pre></div>
<h3 id="except_tuple.py">except_tuple.py</h3>
<p>Now you except tuple in exception handler.</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">try</span>:
         x <span class="op">=</span> <span class="bu">int</span>(s)
         <span class="bu">print</span>(<span class="st">&quot;Conversion is successful!&quot;</span>)
    <span class="cf">except</span> (<span class="pp">ValueError</span>, <span class="pp">TypeError</span>):
        x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
        <span class="bu">print</span>(<span class="st">&quot;Conversion is failed!&quot;</span>)
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Conversion</span> is failed!
<span class="ex">Convert</span> String to int -1</code></pre></div>
<h2 id="exceptions-for-programmer-errors">Exceptions for programmer errors</h2>
<ul>
<li>IndentationError</li>
<li>SyntaxError</li>
<li>NameError</li>
</ul>
<p><strong>You should not normally catch these</strong></p>
<h2 id="handle-empty-except-block">Handle empty except block</h2>
<p>The solution arrives in the form of the <strong>pass</strong> keyword, which is a special statement which does precisely nothing. It's a NOOP, and its only purpose is to allow us to construct syntactically permissible blocks which are semantically empty.</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
    <span class="cf">try</span>:
        x <span class="op">=</span> <span class="bu">int</span>(s)
    <span class="cf">except</span> (<span class="pp">ValueError</span>, <span class="pp">TypeError</span>):
        <span class="cf">pass</span>
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Convert</span> String to int -1</code></pre></div>
<h2 id="exception-object-exception_object.py">Exception object (exception_object.py)</h2>
<p>We can get a named reference to the exception object by tacking an as clause onto the end of the except statement</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating exceptions &#39;&#39;&#39;</span>
<span class="im">import</span> sys

<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
    <span class="cf">try</span>:
        x <span class="op">=</span> <span class="bu">int</span>(s)
    <span class="cf">except</span> (<span class="pp">ValueError</span>, <span class="pp">TypeError</span>) <span class="im">as</span> e:
        <span class="bu">print</span>(<span class="st">&quot;Conversion error:</span><span class="sc">{}</span><span class="st">&quot;</span>.<span class="bu">format</span>(<span class="bu">str</span>(e)), <span class="bu">file</span><span class="op">=</span>sys.stderr)
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>]))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Convert</span> String to int -1
<span class="ex">Conversion</span> error:int() <span class="ex">argument</span> must be a string, a bytes-like object or a number, not <span class="st">&#39;list&#39;</span></code></pre></div>
<h2 id="re-raising-exceptions-raise_demo.py">Re-Raising Exceptions (raise_demo.py)</h2>
<p>If you are not willing to handle exception, you can use <strong>raise</strong> to throw it back to caller</p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating raise &#39;&#39;&#39;</span>
<span class="im">import</span> sys

<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">try</span>:
        <span class="cf">return</span> <span class="bu">int</span>(s)
    <span class="cf">except</span> (<span class="pp">ValueError</span>, <span class="pp">TypeError</span>) <span class="im">as</span> e:
        <span class="bu">print</span>(<span class="st">&quot;Conversion error:</span><span class="sc">{}</span><span class="st">&quot;</span>.<span class="bu">format</span>(<span class="bu">str</span>(e)), <span class="bu">file</span><span class="op">=</span>sys.stderr)
        <span class="cf">raise</span>

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;1,234&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Conversion</span> error:invalid literal for int() <span class="ex">with</span> base 10: <span class="st">&#39;1,234&#39;</span>
<span class="ex">Traceback</span> (most recent call last)<span class="bu">:</span>
  <span class="ex">File</span> <span class="st">&quot;raise_demo.py&quot;</span>, line 13, in <span class="op">&lt;</span>module<span class="op">&gt;</span>
    <span class="ex">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;1,234&quot;</span>))
  <span class="ex">File</span> <span class="st">&quot;raise_demo.py&quot;</span>, line 7, in convert
    <span class="bu">return</span> int(s)
<span class="ex">ValueError</span>: invalid literal for int() <span class="ex">with</span> base 10: <span class="st">&#39;1,234&#39;</span></code></pre></div>
<h2 id="returning-exception-objects">Returning exception objects</h2>
<p>You can throw an exception object from the code</p>
<h3 id="raise_demo_1.py">raise_demo_1.py</h3>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating raise &#39;&#39;&#39;</span>
<span class="im">import</span> sys

<span class="kw">def</span> div(x, y):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">if</span> y <span class="op">==</span> <span class="dv">0</span>:
        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">&quot;y cannot be zero </span><span class="sc">{}</span><span class="st">&quot;</span>.<span class="bu">format</span>(y))
    <span class="cf">return</span> x <span class="op">/</span> y

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Division div(10,5) &quot;</span>, div(<span class="dv">10</span>, <span class="dv">5</span>))
    <span class="bu">print</span>(<span class="st">&quot;Division div(10,0)&quot;</span>, div(<span class="dv">10</span>, <span class="dv">0</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Division</span> div(10,5)  <span class="ex">2.0</span>
<span class="ex">Traceback</span> (most recent call last)<span class="bu">:</span>
    <span class="ex">print</span>(<span class="st">&quot;Division div(10,0)&quot;</span>, div(10, 0))
    <span class="ex">raise</span> ValueError(<span class="st">&quot;y cannot be zero {}&quot;</span>.format(y))
<span class="ex">ValueError</span>: y cannot be zero 0</code></pre></div>
<h3 id="raise_demo_2.py">raise_demo_2.py</h3>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating raise &#39;&#39;&#39;</span>
<span class="im">import</span> sys

<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">if</span> <span class="kw">not</span> <span class="bu">isinstance</span>(s, <span class="bu">int</span>):
        <span class="cf">raise</span> <span class="pp">TypeError</span>(<span class="st">&quot;Argument </span><span class="sc">{}</span><span class="st"> must be number&quot;</span>.<span class="bu">format</span>(s))
    <span class="cf">return</span> <span class="bu">int</span>(s)

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;abc&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Traceback</span> (most recent call last)<span class="bu">:</span>
  <span class="ex">File</span> <span class="st">&quot;raise_demo_2.py&quot;</span>, line 11, in <span class="op">&lt;</span>module<span class="op">&gt;</span>
    <span class="ex">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;abc&quot;</span>))
  <span class="ex">File</span> <span class="st">&quot;raise_demo_2.py&quot;</span>, line 7, in convert
    <span class="ex">raise</span> TypeError(<span class="st">&quot;Argument {} must be number&quot;</span>.format(s))
<span class="ex">TypeError</span>: Argument abc must be number</code></pre></div>
<h2 id="finally-block">Finally block</h2>
<p>Code in the finally-block is executed whether execution leaves the try-block normally by reaching the end of the block or exceptionally by an exception being raised.<br />
<strong>finally-block is executed no matter how the try-block exits</strong></p>
<div class="sourceCode"><pre class="sourceCode python"><code class="sourceCode python"><span class="co">&#39;&#39;&#39; A module for demonstrating finally block &#39;&#39;&#39;</span>
<span class="kw">def</span> convert(s):
    <span class="co">&#39;&#39;&#39; convert string to an integer &#39;&#39;&#39;</span>
    <span class="cf">try</span>:
         x <span class="op">=</span> <span class="bu">int</span>(s)
         <span class="bu">print</span>(<span class="st">&quot;Conversion is successful!&quot;</span>)
    <span class="cf">except</span> <span class="pp">ValueError</span>:
        x <span class="op">=</span> <span class="op">-</span><span class="dv">1</span>
        <span class="bu">print</span>(<span class="st">&quot;Conversion is failed!&quot;</span>)
    <span class="cf">finally</span>:
        <span class="bu">print</span>(<span class="st">&quot;This block is always called&quot;</span>)    
    <span class="cf">return</span> x

<span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">&quot;__main__&quot;</span>:
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;10&quot;</span>))
    <span class="bu">print</span>(<span class="st">&quot;Convert String to int&quot;</span>, convert(<span class="st">&quot;Hello world&quot;</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode bash"><code class="sourceCode bash"><span class="ex">Conversion</span> is successful!
<span class="ex">This</span> block is always called
<span class="ex">Convert</span> String to int 10
<span class="ex">Conversion</span> is failed!
<span class="ex">This</span> block is always called
<span class="ex">Convert</span> String to int -1</code></pre></div>
<h2 id="summary">Summary</h2>
<ul>
<li>Raising an exception interrupts normal program !ow and<br />
transfers control to an exception handler.</li>
<li>Exception handlers de&quot;ned using the try...except<br />
construct.</li>
<li>try blocks define a context for detecting exceptions.</li>
<li>Corresponding except blocks handle speci&quot;c exception<br />
types.</li>
<li>Python uses exceptions pervasively.</li>
<li>Many built-in language features depend on them.</li>
<li>except blocks can capture an exception, which are often of<br />
a standard type.</li>
<li>Programmer errors should not normally be handled.</li>
<li>Exceptional conditions can be signaled using raise.</li>
<li>raise without an argument re-raises the current<br />
exception.</li>
<li>Generally do not check for TypeErrors.</li>
<li>Exception objects can be converted to strings using str().</li>
<li>A function’s exceptions form part of its API.</li>
<li>They should be documented properly.</li>
<li>Prefer to use built-in exception types when possible.</li>
<li>Use the try...finally construct to perform cleanup<br />
actions.</li>
<li>May be used in conjunction with except blocks.<br />
Output of print() can be redirected using the optional<br />
file argument.</li>
<li>Use and and or for combining boolean expressions.</li>
<li>Return codes are too easily ignored.</li>
<li>Platform-specific actions can be implemented using EAFP<br />
along with catching ImportErrors.</li>
</ul>
<h2 id="exisiting-exceptions">Exisiting Exceptions</h2>
<p>Often if you're deciding what exceptions your code should raise, you should look for similar cases in existing code. The more your code follows existing patterns, the easier it will be for people to integrate and understand.</p>
<ul>
<li>KeyError to indicate a request for a nonexistent key because this is how dictionary works</li>
<li>IndexError is raised when an integer index is out of range</li>
<li>ValueError is raised when the object is of the right type, but contains an inappropriate value</li>
</ul>
<h3 id="index"><a href="index.html">index</a></h3>
</body>
</html>
